### PR TITLE
Remove align-items css rule

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Connected to #3

Remove align-items css rule causing `vaadin-nav-scroller` not to stretch to the full height

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-nav/17)

### CODE REVIEW

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/17#-:-Kvg5XbQd9ui4Sh7HT_h:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/17#-:-Kvg9yhQLFHdN9MIkhxM:bnfp4nl)*

**Comment by tomivirkki** [comment]
Visual tests broken, merge once those pass

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/17#-:-KvgA3eihWJCVi06Qqhg:b-tvznig)*

**Comment by YuriyVaadin** [comment]
Done, but there is still a random 'Timed Out' error in tests.

---

Review status: 1 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/17#-:-Kvh1DWVf-vHJCfHahA-:b-opuy8d)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/17)*

**Pull request merged**
