### PR TITLE
Change API for direction and hidden attributes. Make buttons work in vertical.

### PR DESCRIPTION
**Pull request by manolo**
Connected to #3 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-nav/13)

### CODE REVIEW

**Comment by limonte** [comment]
For me arrow down is always visible, even if the last item is focused:



Expected: arrow down is hidden when the last item is focused.

**Comment by manolo** [comment]
what browser?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-:-Kveyg8eipCyIOnLx566:bnod9u6)*

**Comment by limonte** [comment]
if not specified, then it's the default one :) Chrome/Linux

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-:-Kvf3Xb_mw3lEddTfKH0:b13ffex)*

**Comment by manolo** [comment]
@limonte fixed

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-:-KvfXx_m9zD0idoKjbmU:beac6m1)*

**Comment by limonte** [comment]
> For me arrow down is always visible, even if the last item is focused:

Fixed now :+1:

---

Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-nav.html, line 148 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-KvfYbLapYk53PBg69pm:-KvfYbLapYk53PBg69pn:b-6q8r38) ([raw file](https://github.com/vaadin/vaadin-nav/blob/bb3bb1f7db9684bb6b9b71978a4e55f131ccf6ce/vaadin-nav.html#L148)):*
> ```HTML
>         }
> 
>         _incrementScroll(pixels) {
> ```

`increment` is a confusing word, increment means increasing or addition but `pixels` could be both positive and negative. Just `_scroll()` will be better.

---

*[vaadin-nav.html, line 170 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-KvfZP4rUYef5ixQhPFl:-KvfZP4rUYef5ixQhPFm:bjsdcg6) ([raw file](https://github.com/vaadin/vaadin-nav/blob/bb3bb1f7db9684bb6b9b71978a4e55f131ccf6ce/vaadin-nav.html#L170)):*
> ```HTML
>           this.$.backButton.style.transform = 'translateZ(0)';
>           this.$.forwardButton.style.transform = 'translate3d(0, 0, 0)';
>           this.$.forwardButton.style.transform = 'translateZ(0)';
> ```

I don't like that from the very beginning the component contains browser-specific hacks. Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-:-KvfXwDYNKrfzlyZ_ECr:b-25yn5g)*

**Comment by manolo** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-nav.html, line 148 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-KvfYbLapYk53PBg69pm:-KvfgVzKZTqMgzkDpQFx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-nav/blob/bb3bb1f7db9684bb6b9b71978a4e55f131ccf6ce/vaadin-nav.html#L148)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`increment` is a confusing word, increment means increasing or addition but `pixels` could be both positive and negative. Just `_scroll()` will be better.
</blockquote></details>

Done.

---

*[vaadin-nav.html, line 170 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-KvfZP4rUYef5ixQhPFl:-KvfgWLM6OmwpxiJI9rw:b-n4cmjf) ([raw file](https://github.com/vaadin/vaadin-nav/blob/bb3bb1f7db9684bb6b9b71978a4e55f131ccf6ce/vaadin-nav.html#L170)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I don't like that from the very beginning the component contains browser-specific hacks. Not a blocker.
</blockquote></details>

Me neither, but didn't get a better option so far. Maybe @platosha or @tomivirkki  ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13)*

**Comment by tomivirkki** [comment]
Review status: 0 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-nav.html, line 170 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-KvfZP4rUYef5ixQhPFl:-Kvfned5UBx5WKp4sAB_:bn7vho0) ([raw file](https://github.com/vaadin/vaadin-nav/blob/bb3bb1f7db9684bb6b9b71978a4e55f131ccf6ce/vaadin-nav.html#L170)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Me neither, but didn't get a better option so far. Maybe @platosha or @tomivirkki  ?
</blockquote></details>

Is it the same issue as https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-text-field.html#L406 ?
Rather use the same approach. Forcing button transforms programmatically makes it harder to theme them.

---

*[vaadin-nav.html, line 76 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-KvfoM8q9uzq6Q4Th-BU:-KvfoM8q9uzq6Q4Th-BV:b-pds9dn) ([raw file](https://github.com/vaadin/vaadin-nav/blob/92066d16a83f5cbde4460691dd70f1f1ed114835/vaadin-nav.html#L76)):*
> ```HTML
> 
>       :host([vertical]) [part="back-button"]::after {
>         content: '▲';
> ```

These icons aren't very consistent. How about:
```
[part="back-button"]::after,
[part=“forward-button"]::after {
  content: '';
  border: 6px solid transparent;
  font-size: 0;
}

:host([vertical]) [part="forward-button"]::after {
  border-top-color: #444;
}

...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13)*

**Comment by manolo** [comment]
Review status: 0 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-nav.html, line 170 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-KvfZP4rUYef5ixQhPFl:-Kvfy6hlBVNfJlxybxSM:b-896fix) ([raw file](https://github.com/vaadin/vaadin-nav/blob/bb3bb1f7db9684bb6b9b71978a4e55f131ccf6ce/vaadin-nav.html#L170)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is it the same issue as https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-text-field.html#L406 ?
Rather use the same approach. Forcing button transforms programmatically makes it harder to theme them.
</blockquote></details>

Done.

---

*[vaadin-nav.html, line 76 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-KvfoM8q9uzq6Q4Th-BU:-KvfxfMb15Hi3Vueg4dv:bkxufii) ([raw file](https://github.com/vaadin/vaadin-nav/blob/92066d16a83f5cbde4460691dd70f1f1ed114835/vaadin-nav.html#L76)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

These icons aren't very consistent. How about:
```
[part="back-button"]::after,
[part=“forward-button"]::after {
  content: '';
  border: 6px solid transparent;
  font-size: 0;
}

:host([vertical]) [part="forward-button"]::after {
  border-top-color: #444;
}

...
```
</blockquote></details>

All styling here is just to make the component work, and demonstrate that we can set icons by CSS.
@jouni is working on styling. I think it's better to make all definitive changes in a separated PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13)*

**Comment by limonte** [comment]
Review status: 0 of 21 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[wct.conf.js, line 5 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-Kvfz-bNTz0NHdh9OFn3:-Kvfz-bOC2GvluxilLAB:b-hn2gds) ([raw file](https://github.com/vaadin/vaadin-nav/blob/d5f316c21a5e373f4429e0d70f90173396f128eb/wct.conf.js#L5)):*
> ```JavaScript
> module.exports = {
>   plugins: {
>     'random-output': true
> ```

Why do you need `random-output`? It's useful only for big components with a lot of tests like `grid`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13)*

**Comment by manolo** [comment]
Review status: 0 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[wct.conf.js, line 5 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-Kvfz-bNTz0NHdh9OFn3:-Kvg-ZZbK3tZc-xB5Cuo:b-dq2zu8) ([raw file](https://github.com/vaadin/vaadin-nav/blob/d5f316c21a5e373f4429e0d70f90173396f128eb/wct.conf.js#L5)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Why do you need `random-output`? It's useful only for big components with a lot of tests like `grid`.
</blockquote></details>

I'm trying to make tests pass, there are timeouts in iphone repeated in several builds

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13)*

**Comment by manolo** [comment]
Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[wct.conf.js, line 5 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-Kvfz-bNTz0NHdh9OFn3:-Kvg1fVovUaw8AubpGij:bwnyd42) ([raw file](https://github.com/vaadin/vaadin-nav/blob/d5f316c21a5e373f4429e0d70f90173396f128eb/wct.conf.js#L5)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I'm trying to make tests pass, there are timeouts in iphone repeated in several builds
</blockquote></details>

Removed, testing in separated temporary branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 16 files at r2, 7 of 12 files at r3, 12 of 12 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-nav.html, line 141 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-KvgV1LzecKSf0_RXZZT:-KvgV1LzecKSf0_RXZZU:brydqwv) ([raw file](https://github.com/vaadin/vaadin-nav/blob/63e662a18ec388f06076a18744d6a8f37d555cb8/vaadin-nav.html#L141)):*
> ```HTML
>         ready() {
>           super.ready();
>           window.addEventListener('resize', () => this._updateOverflow());
> ```

`Polymer.IronResizableBehavior` should not be extended in case we are going back to use `resize` event listener instead of listener to `iron-resize`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-:-KvgVuE3CpOlyYO6fCrP:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[vaadin-nav.html, line 76 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-KvfoM8q9uzq6Q4Th-BU:-KvgWBs3NC3PmY9uwAK8:beezx4k) ([raw file](https://github.com/vaadin/vaadin-nav/blob/92066d16a83f5cbde4460691dd70f1f1ed114835/vaadin-nav.html#L76)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

All styling here is just to make the component work, and demonstrate that we can set icons by CSS.
@jouni is working on styling. I think it's better to make all definitive changes in a separated PR.
</blockquote></details>

Ok, got it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13)*

**Comment by manolo** [comment]
Review status: 21 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-nav.html, line 141 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-KvgV1LzecKSf0_RXZZT:-KvgewbYJwU5cqaH1jQ-:b-8lhpmo) ([raw file](https://github.com/vaadin/vaadin-nav/blob/63e662a18ec388f06076a18744d6a8f37d555cb8/vaadin-nav.html#L141)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

`Polymer.IronResizableBehavior` should not be extended in case we are going back to use `resize` event listener instead of listener to `iron-resize`
</blockquote></details>

Ups, merging mistake. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13)*

**Comment by YuriyVaadin** [comment]
Reviewed 2 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13)*

**Comment by limonte** [comment]
Reviewed 2 of 4 files at r1, 2 of 16 files at r2, 6 of 12 files at r3, 1 of 12 files at r5, 1 of 3 files at r6, 9 of 9 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 16 files at r2, 6 of 12 files at r3, 1 of 12 files at r5, 1 of 3 files at r6, 9 of 9 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/13#-:-KvkWRN3tRu0tciKjky2:bnfp4nl)*

**Pull request merged**
