### PR TITLE
Remove resize listener, extend iron-resizable-behavior

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Connected to #3 

Remove `resize` listener, extend iron-resizable-behavior

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-nav/12)

### CODE REVIEW

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/12#-:-KvbHeiPOImI4gk2yIiU:bnfp4nl)*

**Comment by limonte** [comment]
Very nice syntax:

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/12#-:-KvbgPgmhuCOL6P9ynZu:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/12#-:-KvfEWnImdo6w0vKWlcq:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[vaadin-nav.html, line 112 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-nav/12#-KvfFLVX91e7o93gzAWq:-KvfFLVYlLU6lthANEx2:b-oqxswk) ([raw file](https://github.com/vaadin/vaadin-nav/blob/1ad7f277413487e5f289a3c94a49c6088ab1a6ee/vaadin-nav.html#L112)):*
> ```HTML
>        * @mixes Vaadin.NavListMixin
>        * @mixes Vaadin.ThemableMixin
>        * @mixes Polymer.IronResizableBehavior
> ```

Should we drop @mixes annotations for ThemableMixin and IronResizableBehavior? Otherwise their apis will end up in our docs: https://www.dropbox.com/s/l9wyrdtcmbi87az/Screenshot%202017-10-05%2009.37.31.png?dl=0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/12)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-nav.html, line 112 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-nav/12#-KvfFLVX91e7o93gzAWq:-KvfJNMmqq5WVEJZJaiC:bk0274c) ([raw file](https://github.com/vaadin/vaadin-nav/blob/1ad7f277413487e5f289a3c94a49c6088ab1a6ee/vaadin-nav.html#L112)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should we drop @mixes annotations for ThemableMixin and IronResizableBehavior? Otherwise their apis will end up in our docs: https://www.dropbox.com/s/l9wyrdtcmbi87az/Screenshot%202017-10-05%2009.37.31.png?dl=0
</blockquote></details>

We always include the ThemableMixin in all our elements, it should not introduce any public API in the doc, but I think the reference that the element implements the mixin is useful.
Related with the resizable, I think it's nice that the user knows that this element needs resizing notifications and works well in a resizable tree. But we are not documenting it in other documents, so I think we should align with them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/12)*

**Comment by tomivirkki** [comment]
*[vaadin-nav.html, line 112 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-nav/12#-KvfFLVX91e7o93gzAWq:-KvfNXabeiazpbfiaATE:b-xa0rd5) ([raw file](https://github.com/vaadin/vaadin-nav/blob/1ad7f277413487e5f289a3c94a49c6088ab1a6ee/vaadin-nav.html#L112)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

We always include the ThemableMixin in all our elements, it should not introduce any public API in the doc, but I think the reference that the element implements the mixin is useful.
Related with the resizable, I think it's nice that the user knows that this element needs resizing notifications and works well in a resizable tree. But we are not documenting it in other documents, so I think we should align with them.
</blockquote></details>

Yep, there's already a fix for the first issue https://github.com/vaadin/vaadin-themable-mixin/pull/19. So drop `@mixes Polymer.IronResizableBehavior` and we're good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/12)*

**Comment by YuriyVaadin** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-nav.html, line 112 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-nav/12#-KvfFLVX91e7o93gzAWq:-KvfNwcQl7nf1b6Yjm4b:b-896fix) ([raw file](https://github.com/vaadin/vaadin-nav/blob/1ad7f277413487e5f289a3c94a49c6088ab1a6ee/vaadin-nav.html#L112)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Yep, there's already a fix for the first issue https://github.com/vaadin/vaadin-themable-mixin/pull/19. So drop `@mixes Polymer.IronResizableBehavior` and we're good
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/12)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/12)*

**Pull request merged**
