### PR TITLE
Implement focus by first letter. Fix Edge & IE11.

### PR DESCRIPTION
**Pull request by manolo**
Connected to #3 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-nav/9)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/9#-:-KvVve-MvYfHo_odmE6H:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/9#-:-KvWbvgpYF4-Y6Q3Nlpp:bnfp4nl)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-nav-list-mixin.html, line 85 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-nav/9#-KvXbKg5FbZ0VOY_JgZL:-KvXbKg5FbZ0VOY_JgZM:bt2luph) ([raw file](https://github.com/vaadin/vaadin-nav/blob/7dcc6c2707b387e0a765ec864854ef3843727fff/vaadin-nav-list-mixin.html#L85)):*
> ```HTML
>         increment = 1;
>         idx = currentIdx + 1;
>         condition = (event, item) => item.textContent.toLowerCase().indexOf(key.toLowerCase()) == 0;
> ```

`event` argument is defined but never used.

---

*[vaadin-nav-list-mixin.html, line 89 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-nav/9#-KvXc5x3RfyOZY1IkIap:-KvXc5x3RfyOZY1IkIaq:b8nsnae) ([raw file](https://github.com/vaadin/vaadin-nav/blob/7dcc6c2707b387e0a765ec864854ef3843727fff/vaadin-nav-list-mixin.html#L89)):*
> ```HTML
> 
>       if (increment) {
>         this._moveFocus(event, items, idx, increment, condition);
> ```

BTW kinda feels unnecessary complex to call a separate method here now that you have to pass all the local variables as arguments. Would prefer to simply have `_moveFocus` contents right here instead.

As a matter of taste, not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/9)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-nav-list-mixin.html, line 85 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-nav/9#-KvXbKg5FbZ0VOY_JgZL:-KvXizUFVN2cXBHdZKxp:b-896fix) ([raw file](https://github.com/vaadin/vaadin-nav/blob/7dcc6c2707b387e0a765ec864854ef3843727fff/vaadin-nav-list-mixin.html#L85)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

`event` argument is defined but never used.
</blockquote></details>

Done.

---

*[vaadin-nav-list-mixin.html, line 89 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-nav/9#-KvXc5x3RfyOZY1IkIap:-KvXiuErTCmL9Z2wRwlV:b-896fix) ([raw file](https://github.com/vaadin/vaadin-nav/blob/7dcc6c2707b387e0a765ec864854ef3843727fff/vaadin-nav-list-mixin.html#L89)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW kinda feels unnecessary complex to call a separate method here now that you have to pass all the local variables as arguments. Would prefer to simply have `_moveFocus` contents right here instead.

As a matter of taste, not a blocker.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/9)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-nav/9#-:-Kva_QSK-i0RzokvMDmy:bnfp4nl)*

**Pull request merged**
